[package]
name = "oottracker"
version = "0.1.6"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
bitflags = "1"
byteorder = "1"
collect-mac = "0.1"
futures = "0.3"
itertools = "0.9"
pin-utils = "0.1"
semver = "0.11"
smart-default = "0.6"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static]
path = "../ootr-static"

[dependencies.oottracker-derive]
path = "../oottracker-derive"

[dependencies.tokio]
version = "1"
features = ["net"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.async-proto]
#version = "0.3" #TODO publish changes
path = "C:\\Users\\fenhl\\git\\github.com\\fenhl\\async-proto\\stage\\crate\\async-proto"
features = ["blocking"]
