[package]
name = "oottracker"
version = "0.2.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
bitflags = "1"
byteorder = "1"
collect-mac = "0.1"
directories = "3"
enum-iterator = "0.6"
futures = "0.3"
itertools = "0.10"
pin-utils = "0.1"
semver = "0.11"
serde_json = "1"
smart-default = "0.6"

[dependencies.async-proto]
version = "0.4"
features = ["blocking"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static] # used in tests
path = "../ootr-static"

[dependencies.oottracker-derive]
path = "../oottracker-derive"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["fs", "net"]
