[package]
name = "oottracker"
version = "0.1.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
async-trait = "0.1"
bitflags = "1"
byteorder = "1"
futures = "0.3"
pin-utils = "0.1"
semver = "0.11"
smart-default = "0.6"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.oottracker-derive]
path = "../oottracker-derive"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "0.2"
features = ["io-util", "net"]
