[package]
name = "oottracker"
version = "0.6.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
async-stream = "0.3"
bitflags = "1"
byteorder = "1"
collect-mac = "0.1"
derivative = "2"
directories = "3"
eventsource-client = "0.6"
futures = "0.3"
#horrorshow = "0.8" #TODO PR changes, wait for publish
iced = "0.3"
image = "0.23"
itertools = "0.10"
once_cell = "1"
rocket = "0.5.0-rc.1"
semver = "1"
serde_json = "1"

[dependencies.async-proto]
version = "0.8"
features = ["serde_json", "tokio-tungstenite", "write-sync"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.enum-iterator]
git = "https://github.com/dasgefolge/enum-iterator"
branch = "fields"

[dependencies.horrorshow]
git = "https://github.com/fenhl/horrorshow-rs"
branch = "rocket"
features = ["rocket"]

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static] # used in tests
path = "../ootr-static"

[dependencies.oottracker-derive]
path = "../oottracker-derive"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls", "trust-dns"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["fs", "net", "sync", "time"]

[dependencies.tokio-stream]
version = "0.1"
features = ["net"]

[dependencies.tokio-tungstenite]
version = "0.15"
features = ["rustls-tls"]

[dependencies.url]
version = "2"
features = ["serde"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
default-features = false
