[package]
name = "ootr-static"
version = "0.6.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
once_cell = "1"
semver = "1"

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static-derive]
path = "../ootr-static-derive"
