[package]
name = "ootr-static"
version = "0.3.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
lazy_static = "1"
semver = "0.11"

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static-derive]
path = "../ootr-static-derive"
