[package]
name = "oottracker-derive"
version = "0.5.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.4"
itertools = "0.10"
proc-macro2 = "1"
quote = "1"
syn = "1"
