[package]
name = "oottracker-derive"
version = "0.7.3"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.5"
itertools = "0.10"
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "1"
features = ["extra-traits"]
