[package]
name = "oottracker-derive"
version = "0.7.4"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
convert_case = "0.6"
itertools = "0.13"
proc-macro2 = "1"
quote = "1"

[dependencies.syn]
version = "2"
features = ["extra-traits"]
