[package]
name = "oottracker-web"
version = "0.4.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
itertools = "0.10"
smart-default = "0.6"

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static]
path = "../ootr-static"

[dependencies.oottracker]
path = "../oottracker"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
branch = "master"

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.tokio]
version = "1"
features = ["sync"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
