[package]
name = "oottracker-web"
version = "0.6.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
futures = "0.3"
#horrorshow = "0.8" #TODO PR changes, wait for publish
iced_core = "0.4"
rocket = "0.5.0-rc.1"
warp = "0.3"

[dependencies.async-proto]
version = "0.8"
features = ["warp"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.horrorshow]
git = "https://github.com/fenhl/horrorshow-rs"
branch = "rocket"
features = ["rocket"]

[dependencies.ootr]
path = "../ootr"

[dependencies.oottracker]
path = "../oottracker"

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.tokio]
version = "1"
features = ["sync"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
