[package]
name = "oottracker-bizhawk"
version = "0.6.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
semver = "1"

[dependencies.winver]
git = "https://github.com/fenhl/winver"
branch = "main"
