[package]
name = "ootr"
version = "0.2.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
semver = "0.11"

[dependencies.async-proto]
version = "0.4"
features = ["blocking"]

[dependencies.quote-value]
git = "https://github.com/fenhl/quote-value" #TODO publish
branch = "main"
