[package]
name = "oottracker-utils"
version = "0.2.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "oottracker-format-ram"
path = "src/format_ram.rs"

[[bin]]
name = "oottracker-release"
path = "src/release.rs"

[[bin]]
name = "oottracker-version-bump"
path = "src/version_bump.rs"

[dependencies]
async-trait = "0.1"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.tokio]
version = "1"
features = ["fs", "io-util", "macros", "process", "rt-multi-thread"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"

[target.'cfg(windows)'.dependencies]
dir-lock = "0.3"
itertools = "0.10"
plist = "1"
serde_json = "1"
tempfile = "3"
zip = "0.5"

[target.'cfg(windows)'.dependencies.ootr]
path = "../ootr"

[target.'cfg(windows)'.dependencies.ootr-dynamic]
path = "../ootr-dynamic"

[target.'cfg(windows)'.dependencies.ootr-static]
path = "../ootr-static"

[target.'cfg(windows)'.dependencies.oottracker]
path = "../oottracker"

[target.'cfg(windows)'.dependencies.oottracker-bizhawk]
path = "../oottracker-bizhawk"

#[target.'cfg(windows)'.dependencies.oottracker-csharp] #TODO
#path = "../oottracker-csharp"

[target.'cfg(windows)'.dependencies.oottracker-web]
path = "../oottracker-web"

[target.'cfg(windows)'.dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "rustls-tls"]

[target.'cfg(windows)'.dependencies.semver]
version = "0.11"
features = ["serde"]

[target.'cfg(windows)'.dependencies.serde]
version = "1"
features = ["derive"]

[target.'cfg(windows)'.dependencies.structopt]
version = "0.3"
features = ["paw"]

[target.'cfg(windows)'.dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
default-features = false
