[package]
name = "oottracker-utils"
version = "0.1.6"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "oottracker-format-ram"
path = "src/format_ram.rs"

[[bin]]
name = "oottracker-release"
path = "src/release.rs"

[dependencies]
async-trait = "0.1"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.tokio]
version = "0.2" #TODO upgrade to 0.3 once supported by reqwest
features = ["fs", "io-util", "macros", "process", "rt-threaded"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"

[target.'cfg(windows)'.dependencies]
dir-lock = "0.2"
itertools = "0.9"
semver = "0.11"
serde_json = "1"
tempfile = "3"
zip = "0.5"

[target.'cfg(windows)'.dependencies.oottracker]
path = "../oottracker"

[target.'cfg(windows)'.dependencies.oottracker-bizhawk]
path = "../oottracker-bizhawk"

#[target.'cfg(windows)'.dependencies.oottracker-csharp] #TODO
#path = "../oottracker-csharp"

[target.'cfg(windows)'.dependencies.reqwest]
version = "0.10"
default-features = false
features = ["json", "rustls-tls"]

[target.'cfg(windows)'.dependencies.serde]
version = "1"
features = ["derive"]
