[package]
name = "oottracker-utils"
version = "0.1.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "oottracker-release"
path = "src/release.rs"

[dependencies]
async-trait = "0.1"
dir-lock = "0.2"
semver = "0.11"
serde_json = "1"
tempfile = "3"
zip = "0.5"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.oottracker]
path = "../oottracker"

[dependencies.reqwest]
version = "0.10"
default-features = false
features = ["json", "rustls-tls"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "0.2" #TODO upgrade to 0.3 once supported by reqwest
features = ["fs", "io-util", "macros", "process", "rt-threaded"]
