[package]
name = "oottracker-csharp"
version = "0.1.4"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "oottracker"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
semver = "0.11"

[dependencies.oottracker]
path = "../oottracker"
