[package]
name = "oottracker-csharp"
version = "0.4.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "oottracker"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10"
libc = "0.2"
semver = "0.11"

[dependencies.async-proto]
version = "0.7"
features = ["write-sync"]

[dependencies.ootr]
path = "../ootr"

[dependencies.ootr-static]
path = "../ootr-static"

[dependencies.oottracker]
path = "../oottracker"
