[package]
name = "oottracker-csharp"
version = "0.6.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "oottracker"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10"
libc = "0.2"
semver = "1"

[dependencies.async-proto]
#version = "0.8"
path = "C:\\Users\\fenhl\\git\\github.com\\fenhl\\async-proto\\stage\\crate\\async-proto" #TODO publish changes
features = ["write-sync"]

[dependencies.oottracker]
path = "../oottracker"
