[package]
name = "oottracker-csharp"
version = "0.3.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "oottracker"
crate-type = ["cdylib"]

[dependencies]
async-proto = "0.5"
itertools = "0.10"
libc = "0.2"
semver = "0.11"

[dependencies.ootr]
path = "../ootr"

[dependencies.oottracker]
path = "../oottracker"
