[package]
name = "oottracker-csharp"
version = "0.6.2"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "oottracker"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10"
libc = "0.2"
semver = "1"

[dependencies.async-proto]
version = "0.8"
features = ["write-sync"]

[dependencies.oottracker]
path = "../oottracker"
