[package]
name = "oottracker-gui"
version = "0.1.6"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
futures = "0.3"
iced_futures = "0.1"
itertools = "0.9"
num-traits = "0.2"

[dependencies.iced]
version = "0.1"
features = ["image", "tokio"]

[dependencies.oottracker]
path = "../oottracker"

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_native = "0.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "0.2"  #TODO upgrade to 0.3 once supported by iced
features = ["net", "stream", "time"]
