[package]
name = "oottracker-gui"
version = "0.1.6"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
futures = "0.3"
iced_futures = "0.2"
itertools = "0.9"
lazy_static = "1"
num-traits = "0.2"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.iced]
version = "0.2"
features = ["image", "tokio"]

[dependencies.oottracker]
path = "../oottracker"

[dependencies.oottracker-derive]
path = "../oottracker-derive"

[dependencies.structopt]
version = "0.3"
features = ["paw"]

[dependencies.wheel]
git = "https://github.com/fenhl/wheel"
branch = "main"
default-features = false

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
iced_native = "0.3"
image = "0.23"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "0.3"
features = ["net", "stream", "time"]
